POST http://localhost:3000/user/cadastro
Content-Type: application/json

{
    "name": "vitoria",
    "email": "vitoria@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "vitoria@gmail.com",
    "password": "12345" 
}

###

GET http://localhost:3000/user/68e57cb2cf3ad2ac86f4caba

###
POST http://localhost:3000/user/addExercise/68e57cb2cf3ad2ac86f4caba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTU3Y2IyY2YzYWQyYWM4NmY0Y2FiYSIsImlhdCI6MTc1OTg3MDEzNH0.HisOfbq6U-lBPHuGu3cTfzNTu6l-Q7GEEhKTLE48daI
Content-Type: application/json

{
    "name": "Desenvolvimento com Halter",
    "duration": 10,
    "reps": 8,
    "weight": "12 kilos"
}


###
DELETE http://localhost:3000/user/delete/68e57aeb28e86464e0051816
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTU3Y2IyY2YzYWQyYWM4NmY0Y2FiYSIsImlhdCI6MTc1OTg3MDEzNH0.HisOfbq6U-lBPHuGu3cTfzNTu6l-Q7GEEhKTLE48daI
Content-Type: application/json

###
PUT http://localhost:3000/user/edit/68e57f0d4098cd507a539064 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTU3Y2IyY2YzYWQyYWM4NmY0Y2FiYSIsImlhdCI6MTc1OTg3MDEzNH0.HisOfbq6U-lBPHuGu3cTfzNTu6l-Q7GEEhKTLE48daI
Content-Type: application/json

{
    "name": "Desenvolvimento com Halter",
    "duration": 10,
    "reps": 5,
    "weight": "14 kilos"
}