POST http://localhost:3000/user/cadastro
Content-Type: application/json

{
    "name": "alex",
    "email": "alex@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "alex@gmail.com",
    "password": "12345" 
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTkxNjhkMGY2Y2JhNzQwYmVhYjY4YiIsImlhdCI6MTc2MDU1MjU5MH0.VxaT6HYkXbz-s1gaJT-qk_N0FZerI3wpfmcIhjbTaqU

###
POST http://localhost:3000/user/addExercise/68e9168d0f6cba740beab68b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTkxNjhkMGY2Y2JhNzQwYmVhYjY4YiIsImlhdCI6MTc2MDU1MjU5MH0.VxaT6HYkXbz-s1gaJT-qk_N0FZerI3wpfmcIhjbTaqU
Content-Type: application/json

{
    "name": "elevação frontal",
    "series": 2,
    "reps": 8,
    "weight": "30 kilos",
    "day": "segunda-feira"
}


###
DELETE http://localhost:3000/user/delete/68e917cf0f6cba740beab6a4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTkxNjhkMGY2Y2JhNzQwYmVhYjY4YiIsImlhdCI6MTc2MDEwNjEyN30.DzwpyQvl_gHIwkwMjNlM8RKjNGwC054cFs0UWtgYmFc
Content-Type: application/json

###
PUT http://localhost:3000/user/edit/68e916ee0f6cba740beab694 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTkxNjhkMGY2Y2JhNzQwYmVhYjY4YiIsImlhdCI6MTc2MDEwNjEyN30.DzwpyQvl_gHIwkwMjNlM8RKjNGwC054cFs0UWtgYmFc
Content-Type: application/json

{
    "name": "Cruxifo",
    "series": 2,
    "reps": 9,
    "weight": "55 kilos",
    "day": "segunda-feira"
}

